---
# defaults file for base

base_deb_packages:
  - vim
  - screen
  - mc
  - python-apt

base_admin_team:
- user: msmirnov
  key: "{{ lookup('file', 'msmirnov.pub') }}"
  shell: /bin/bash
  uid: 10000
  groups: ["wheel"]
